CREATE TABLE IF NOT EXISTS chat_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(128) NOT NULL,
    message_type VARCHAR(16) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_chat_memory_conversation
    ON chat_memory (conversation_id);

CREATE TABLE IF NOT EXISTS pending_intents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(128) NOT NULL,
    skill_name VARCHAR(64) NOT NULL,
    sub_task VARCHAR(512) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pending_intents_conversation
    ON pending_intents (conversation_id);
